/* -*- mode: c -*- */

/* This file is part of the APRON Library, released under LGPL license.
   Please read the COPYING file packaged in the distribution  */

quote(C, "\n\
#include \"apron_caml.h\"\n\
")

typedef [abstract,
	 ml2c(camlidl_apron_var_ptr_ml2c),
	 c2ml(camlidl_apron_var_ptr_c2ml)]
struct apron_var_ptr ap_var_t;

ap_var_t ap_var_of_string([string]char* name);
int ap_var_compare(ap_var_t var1, ap_var_t var2);
[string]char* ap_var_to_string(ap_var_t var)
  quote(call,"_res = ((apron_var_ptr)var)->name;");
int ap_var_hash(ap_var_t var);

quote(MLMLI,"(** APRON Variables *)")

quote(MLI,"\n\
val print : Format.formatter -> t -> unit\n\
")
quote(ML,"\n\
let print fmt v = Format.pp_print_string fmt (to_string v)\n\
")


quote(ML,"\n\
external set_var_operations : unit -> unit = \"camlidl_apron_set_var_operations\"\n\
let _ = set_var_operations()\n\
")
