/* -*- mode: c -*- */

quote(C,"#include \"itv_internal.h\"")
quote(C,"#include \"ap_manager.h\"")
quote(C,"#include \"apron_caml.h\"")

import "manager.idl";

quote(MLMLI,"(** ITV: intervals abstract domain *)")

quote(MLI,"\n(** Create an Itv manager. *)")
ap_manager_ptr itv_manager_alloc();
