/* -*- mode: c -*- */

/* This file is part of the APRON Library, released under LGPL license.  Please
   read the COPYING file packaged in the distribution */

quote(C,"#include \"pk_internal.h\"")
quote(C,"#include \"pkeq.h\"")
quote(C,"#include \"ap_manager.h\"")
quote(C,"#include \"apron_caml.h\"")

quote(C,"typedef struct pk_internal_t* internal_ptr;")

import "manager.idl";
import "polka.idl";

quote(MLMLI,"(** Linear Equality abstract domain *)")

quote(MLMLI,"\n\
(** Type of conjunctions of linear equalities.\n\
\n\
    Abstract values which are linear equalities have the type \n\
    [t Apron.Abstract0.t] or [t Apron.Abstract1.t].\n\n\
    Managers allocated for linear equalities have the type [t Apron.manager.t].\n\
*)\n\
type t\n\
")

quote(MLI,"\n\n(** Create a NewPolkaEq manager. *)")
ap_manager_ptr pkeq_manager_alloc();

quote(MLI,"\n\n(** Get the internal submanager of a NewPolka manager. *)")
internal_ptr manager_get_internal(ap_manager_ptr man)
  quote(call,"_res = (internal_ptr)man->internal;");
